server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    serverUrl:
      defaultZone: http://127.0.0.1:8761/eureka/